### ISSUE TITLE
Ayri bir provider

### ISSUE THREAD

**Issue by VB10** [Prometheum01/Flutter-Music-App#1]
https://github.com/Prometheum01/Flutter-Music-App/blob/5f86ea172bb99c650644ae1ef60a7c3c61043213/music_app/lib/main.dart#L19

birden cok fazla providerin olunca burada yonetmesi gormesi zor oluyor bu classini ayir bir provdermanager gibi

**Comment by Prometheum01** [comment]
Temizlendi
