### ISSUE TITLE
Build provider

### ISSUE THREAD

**Issue by VB10** [Prometheum01/Flutter-Music-App#3]
https://github.com/Prometheum01/Flutter-Music-App/blob/5f86ea172bb99c650644ae1ef60a7c3c61043213/music_app/lib/widgets/playlist_widget.dart#L20

build icinde listen etemeyecefksen bu normal providerleri init state icinde bir referansa ata veya ihtiyacin olunca kullan

listen edegecin durmlarda ise en ustte listen etme atomic widgetlere bolup her widget kendi icinde alsin

**Comment by Prometheum01** [comment]
Düzeltildi
