### ISSUE TITLE
named, ve nulalble

### ISSUE THREAD

**Issue by VB10** [Prometheum01/Flutter-Music-App#5]
https://github.com/Prometheum01/Flutter-Music-App/blob/5f86ea172bb99c650644ae1ef60a7c3c61043213/music_app/lib/extensions/file_extension.dart#L21

bu eleemant atlar bas aritabilir ondan collection paketi ile kulllan 
isimlendirmler daha mantikli olabilir yorum satiri silelim

**Comment by Prometheum01** [comment]
temizlendi
