### ISSUE TITLE
Parcala ve extension

### ISSUE THREAD

**Issue by VB10** [Prometheum01/Flutter-Music-App#7]
https://github.com/Prometheum01/Flutter-Music-App/blob/5f86ea172bb99c650644ae1ef60a7c3c61043213/music_app/lib/pages/all_songs_page.dart#L51

context.read or context.watch kullan listen durumlari icin
ifli tum widgetleri extract widget ile parcala

**Comment by Prometheum01** [comment]
Düzeltildi
