### ISSUE TITLE
Build icinde method

### ISSUE THREAD

**Issue by VB10** [Prometheum01/Flutter-Music-App#8]
https://github.com/Prometheum01/Flutter-Music-App/blob/5f86ea172bb99c650644ae1ef60a7c3c61043213/music_app/lib/pages/now_playing_page.dart#L35

method build icinde kullanma disari cikar
enumu string ile yapma normal bir enuma cevir
init state icini temiz tut

**Comment by Prometheum01** [comment]
Stringler enuma çevrildi. Method build dışına çıkarıldı.
